import { ISalesService } from '../../core/interfaces/services';
import { Customer, SalesInvoice, SalesInvoiceLine, SalesReturn, SalesReturnLine, ReceiptVoucher } from '../../core/domain/entities';
import { PaginationParams, PaginatedResult, EntityFilter } from '../../core/types';
import { RepositoryFactory } from '../../infrastructure/database/repository-factory';
import { queueOfflineWrite } from '../../infrastructure/sync/sync-service';
import { postDoubleEntry } from './accounting-helpers';
import { supabase } from '../../infrastructure/api/supabase';

interface StatementEntry {
  date: string;
  type: string;
  description: string;
  debit: number;
  credit: number;
  balance: number;
}

export class SalesService implements ISalesService {
  private customerRepository = RepositoryFactory.getCustomerRepository();
  private salesInvoiceRepository = RepositoryFactory.getSalesInvoiceRepository();
  private salesInvoiceLineRepository = RepositoryFactory.getSalesInvoiceLineRepository();
  private salesReturnRepository = RepositoryFactory.getSalesReturnRepository();
  private salesReturnLineRepository = RepositoryFactory.getSalesReturnLineRepository();
  private receiptVoucherRepository = RepositoryFactory.getReceiptVoucherRepository();
  private stockMovementRepository = RepositoryFactory.getStockMovementRepository();
  private accountRepository = RepositoryFactory.getAccountRepository();

  async getCustomers(filter?: EntityFilter, params?: PaginationParams): Promise<PaginatedResult<Customer>> {
    return await this.customerRepository.findAll(filter, params);
  }

  async createCustomer(customer: Omit<Customer, 'id' | 'created_at' | 'updated_at'>): Promise<Customer & { client_id?: string }> {
    // The client_id will be auto-generated by the base repository
    const newCustomer = await this.customerRepository.create(customer);
    await queueOfflineWrite('customers', 'insert', newCustomer.id, newCustomer);
    
    // Note: CRM accounts are now created manually by admin, not automatically
    // The admin should:
    // 1. Get the generated client_id from the customer record
    // 2. Create a Supabase auth user with email = customer.email and password = client_id
    // 3. Link the auth user to the customer by setting customers.user_id
    // 4. Assign the client_portal role to the user
    // Clients authenticate using client_id only, no email/password needed from their perspective
    
    // Return the customer with the generated client_id
    return { 
      ...newCustomer, 
      client_id: (newCustomer as any).client_id
    } as Customer & { client_id?: string };
  }

  /**
   * Link an existing Supabase auth user to a customer for CRM access
   * This should be called by the admin after creating the auth user in Supabase
   */
  async linkCrmUserToCustomer(customerId: string, userId: string): Promise<{ success: boolean; error?: string }> {
    try {
      const { error } = await supabase
        .from('customers')
        .update({ user_id: userId })
        .eq('id', customerId);
      
      if (error) throw error;
      
      return { success: true };
    } catch (error) {
      console.error('Error linking CRM user to customer:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to link user'
      };
    }
  }

  async getInvoices(filter?: EntityFilter, params?: PaginationParams): Promise<PaginatedResult<SalesInvoice>> {
    return await this.salesInvoiceRepository.findAll(filter, params);
  }

  async createInvoice(
    invoice: Omit<SalesInvoice, 'id' | 'created_at' | 'updated_at'>,
    lines: Omit<SalesInvoiceLine, 'id' | 'created_at' | 'updated_at'>[],
    warehouseId: string
  ): Promise<SalesInvoice> {
    const newInvoice = await this.salesInvoiceRepository.create(invoice);
    await queueOfflineWrite('sales_invoices', 'insert', newInvoice.id, newInvoice);

    for (const line of lines) {
      const newLine = await this.salesInvoiceLineRepository.create({
        ...line,
        invoice_id: newInvoice.id
      });
      await queueOfflineWrite('sales_invoice_lines', 'insert', newLine.id, newLine);

      // Deduct finished-goods stock, mirroring Sales.tsx handleSaveInvoice:
      // movement_type 'sale_out', negative qty, linked back to the invoice.
      // warehouseId is passed in (not read off the invoice) because
      // sales_invoices has no warehouse_id column — only stock_movements does.
      const movement = await this.stockMovementRepository.create({
        item_id: newLine.item_id,
        warehouse_id: warehouseId,
        qty: -Math.abs(newLine.qty),
        movement_type: 'sale_out',
        batch_no: newInvoice.invoice_no,
        ref_table: 'sales_invoices',
        ref_id: newInvoice.id,
        moved_at: new Date().toISOString()
      });
      await queueOfflineWrite('stock_movements', 'insert', movement.id, movement);
    }

    // Journal entry, mirroring Sales.tsx handleSaveInvoice: cash sales debit
    // the 'cash' category account, credit sales debit 'ar' (accounts
    // receivable); both credit the 'revenue' account for the invoice total.
    const revenueAcc = (await this.accountRepository.findByCategory('revenue'))[0]?.id;
    if (!revenueAcc) {
      console.warn('Revenue account not found, skipping journal entry for invoice:', newInvoice.id);
    } else if (newInvoice.payment_method === 'cash') {
      const cashAcc = (await this.accountRepository.findByCategory('cash'))[0]?.id;
      if (!cashAcc) {
        console.warn('Cash account not found, skipping journal entry for invoice:', newInvoice.id);
      } else {
        await postDoubleEntry({
          refTable: 'sales_invoices',
          refId: newInvoice.id,
          debitAccountId: cashAcc,
          creditAccountId: revenueAcc,
          amount: newInvoice.total,
          date: newInvoice.date
        });
      }
    } else if (newInvoice.payment_method === 'credit') {
      const arAcc = (await this.accountRepository.findByCategory('ar'))[0]?.id;
      if (!arAcc) {
        console.warn('Accounts receivable account not found, skipping journal entry for invoice:', newInvoice.id);
      } else {
        await postDoubleEntry({
          refTable: 'sales_invoices',
          refId: newInvoice.id,
          debitAccountId: arAcc,
          creditAccountId: revenueAcc,
          amount: newInvoice.total,
          date: newInvoice.date
        });
      }
    }

    return newInvoice;
  }

  async updateInvoice(id: string, invoice: Partial<SalesInvoice>): Promise<SalesInvoice> {
    const updatedInvoice = await this.salesInvoiceRepository.update(id, invoice);
    await queueOfflineWrite('sales_invoices', 'update', id, updatedInvoice);
    return updatedInvoice;
  }

  async deleteInvoice(id: string): Promise<void> {
    await this.salesInvoiceRepository.delete(id);
    await queueOfflineWrite('sales_invoices', 'delete', id, { id });
  }

  async getInvoiceLines(invoiceId: string): Promise<SalesInvoiceLine[]> {
    return await this.salesInvoiceLineRepository.findByInvoiceId(invoiceId);
  }

  async createSalesReturn(
    returnData: Omit<SalesReturn, 'id' | 'created_at' | 'updated_at'>,
    lines: Omit<SalesReturnLine, 'id' | 'created_at' | 'updated_at'>[]
  ): Promise<SalesReturn> {
    const newReturn = await this.salesReturnRepository.create(returnData);
    await queueOfflineWrite('sales_returns', 'insert', newReturn.id, newReturn);

    for (const line of lines) {
      const newLine = await this.salesReturnLineRepository.create({
        ...line,
        return_id: newReturn.id
      });
      await queueOfflineWrite('sales_return_lines', 'insert', newLine.id, newLine);
    }

    // NOTE: stock-movement (adding returned qty back to stock) and journal-entry
    // (Revenue/AR reversal) side effects are intentionally left in the Sales
    // component for this pass, matching createInvoice above.

    return newReturn;
  }

  async getReceiptVouchers(filter?: EntityFilter, params?: PaginationParams): Promise<PaginatedResult<ReceiptVoucher>> {
    return await this.receiptVoucherRepository.findAll(filter, params);
  }

  async createReceiptVoucher(voucher: Omit<ReceiptVoucher, 'id' | 'created_at' | 'updated_at'>): Promise<ReceiptVoucher> {
    const newVoucher = await this.receiptVoucherRepository.create(voucher);
    await queueOfflineWrite('receipt_vouchers', 'insert', newVoucher.id, newVoucher);

    // Mirrors Sales.tsx handleSaveReceiptVoucher: mark the linked invoice
    // paid/partially_paid based on the sum of receipt vouchers applied to it.
    if (newVoucher.invoice_id) {
      const invoice = await this.salesInvoiceRepository.findById(newVoucher.invoice_id);
      if (invoice) {
        const customerVouchers = await this.receiptVoucherRepository.findByCustomerId(invoice.customer_id);
        const totalPaid = customerVouchers
          .filter((v) => v.invoice_id === invoice.id)
          .reduce((sum, v) => sum + Number(v.amount), 0);
        const status = totalPaid >= invoice.total ? 'paid' : 'partially_paid';

        const updatedInvoice = await this.salesInvoiceRepository.update(invoice.id, { status });
        await queueOfflineWrite('sales_invoices', 'update', invoice.id, updatedInvoice);
      }
    }

    // Journal entry, mirroring Sales.tsx: debit Cash/Bank (the voucher's
    // account), credit AR.
    const arAcc = (await this.accountRepository.findByCategory('ar'))[0]?.id;
    if (!arAcc) {
      console.warn('Accounts receivable account not found, skipping journal entry for receipt voucher:', newVoucher.id);
    } else {
      await postDoubleEntry({
        refTable: 'receipt_vouchers',
        refId: newVoucher.id,
        debitAccountId: newVoucher.account_id,
        creditAccountId: arAcc,
        amount: newVoucher.amount,
        date: newVoucher.date
      });
    }

    return newVoucher;
  }

  // Ported from Sales.tsx's runCustomerStatement: opening balance (dated at
  // customer registration) + invoices (debit = total) + receipt vouchers
  // (credit = amount) + sales returns (credit = total), filtered to the date
  // range, sorted chronologically for a running balance, then returned
  // newest-first to match the component's display order.
  async getCustomerStatement(customerId: string, startDate: string, endDate: string): Promise<StatementEntry[]> {
    const customer = await this.customerRepository.findById(customerId);
    if (!customer) return [];

    type Entry = Omit<StatementEntry, 'balance'>;
    const transactions: Entry[] = [];

    transactions.push({
      date: customer.created_at.split('T')[0],
      type: 'opening_balance',
      description: 'الرصيد الافتتاحي عند التسجيل',
      debit: Number(customer.opening_balance) || 0,
      credit: 0
    });

    const invoices = await this.salesInvoiceRepository.findByCustomerId(customerId);
    for (const inv of invoices) {
      transactions.push({
        date: inv.date,
        type: 'sales_invoice',
        description: `فاتورة مبيعات رقم ${inv.invoice_no}`,
        debit: Number(inv.total) || 0,
        credit: 0
      });
    }

    const vouchers = await this.receiptVoucherRepository.findByCustomerId(customerId);
    for (const v of vouchers) {
      transactions.push({
        date: v.date,
        type: 'receipt_voucher',
        description: `سند قبض رقم ${v.voucher_no}`,
        debit: 0,
        credit: Number(v.amount) || 0
      });
    }

    const returnsResult = await this.salesReturnRepository.findAll(
      { customer_id: customerId },
      { page: 1, limit: Number.MAX_SAFE_INTEGER }
    );
    for (const r of returnsResult.data) {
      transactions.push({
        date: r.date,
        type: 'sales_return',
        description: `مرتجع مبيعات رقم ${r.return_no}`,
        debit: 0,
        credit: Number(r.total) || 0
      });
    }

    let filtered = transactions;
    if (startDate) {
      filtered = filtered.filter((t) => t.date >= startDate);
    }
    if (endDate) {
      filtered = filtered.filter((t) => t.date <= endDate);
    }

    const chronological = [...filtered].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

    let balance = 0;
    const withBalance: StatementEntry[] = chronological.map((t) => {
      balance += t.debit - t.credit;
      return { ...t, balance };
    });

    return withBalance.reverse();
  }
}
