import { ISalesService } from '../../core/interfaces/services';
import { Customer, SalesInvoice, SalesInvoiceLine, SalesReturn, SalesReturnLine, ReceiptVoucher } from '../../core/domain/entities';
import { PaginationParams, PaginatedResult, EntityFilter, CustomerStatementEntry } from '../../core/types';
import { RepositoryFactory } from '../../infrastructure/database/repository-factory';
import { queueOfflineWrite } from '../../infrastructure/sync/sync-service';
import { postDoubleEntry } from './accounting-helpers';
import { supabase } from '../../infrastructure/api/supabase';
import { RepLedgerService } from './rep-ledger-service';
import { assertSegregationOfDuties } from './segregation-of-duties-guard';

export interface RepIssuanceOptions {
  // When set, the sale is attributed to this rep's stock-in-hand instead of
  // a direct warehouse counter sale — see createInvoice below.
  repUserId: string;
}

export interface CreditOverride {
  // Whoever is about to exceed the customer's credit limit cannot also be
  // the one who authorizes the override — segregation of duties.
  requestedBy: string;
  approvedBy: string;
}

export class SalesService implements ISalesService {
  private customerRepository = RepositoryFactory.getCustomerRepository();
  private salesInvoiceRepository = RepositoryFactory.getSalesInvoiceRepository();
  private salesInvoiceLineRepository = RepositoryFactory.getSalesInvoiceLineRepository();
  private salesReturnRepository = RepositoryFactory.getSalesReturnRepository();
  private salesReturnLineRepository = RepositoryFactory.getSalesReturnLineRepository();
  private receiptVoucherRepository = RepositoryFactory.getReceiptVoucherRepository();
  private repLedgerService = new RepLedgerService();
  private stockMovementRepository = RepositoryFactory.getStockMovementRepository();
  private accountRepository = RepositoryFactory.getAccountRepository();

  async getCustomers(filter?: EntityFilter, params?: PaginationParams): Promise<PaginatedResult<Customer>> {
    return await this.customerRepository.findAll(filter, params);
  }

  async createCustomer(customer: Omit<Customer, 'id' | 'created_at' | 'updated_at'>): Promise<Customer> {
    // The client_id will be auto-generated by the base repository
    const newCustomer = await this.customerRepository.create(customer);
    await queueOfflineWrite('customers', 'insert', newCustomer.id, newCustomer);

    // Note: CRM accounts are now created manually by admin, not automatically
    // The admin should:
    // 1. Get the generated client_id from the customer record
    // 2. Create a Supabase auth user with email = customer.email and password = client_id
    // 3. Link the auth user to the customer by setting customers.user_id
    // 4. Assign the client_portal role to the user
    // Clients authenticate using client_id only, no email/password needed from their perspective
    return newCustomer;
  }

  // Sets the client-portal second factor (see crm-service.ts) — the PIN is
  // hashed client-side and only the hash ever reaches the database.
  async setCustomerPortalPin(customerId: string, pin: string): Promise<void> {
    const { hashPin } = await import('../../shared/utils/pin-hash');
    const portalPinHash = await hashPin(pin);
    const updated = await this.customerRepository.update(customerId, { portal_pin_hash: portalPinHash });
    await queueOfflineWrite('customers', 'update', customerId, updated);
  }

  // Admin-only in practice: the DB trigger (enforce_admin_only_customer_branch)
  // rejects this update server-side unless the actor holds settings:edit, so
  // this is a thin convenience wrapper, not the actual enforcement point.
  async approveCustomer(customerId: string, warehouseId: string): Promise<Customer> {
    const updated = await this.customerRepository.update(customerId, {
      warehouse_id: warehouseId,
      approval_status: 'approved'
    });
    await queueOfflineWrite('customers', 'update', customerId, updated);
    return updated;
  }

  /**
   * Link an existing Supabase auth user to a customer for CRM access
   * This should be called by the admin after creating the auth user in Supabase
   */
  async linkCrmUserToCustomer(customerId: string, userId: string): Promise<{ success: boolean; error?: string }> {
    try {
      const { error } = await supabase
        .from('customers')
        .update({ user_id: userId })
        .eq('id', customerId);
      
      if (error) throw error;
      
      return { success: true };
    } catch (error) {
      console.error('Error linking CRM user to customer:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to link user'
      };
    }
  }

  async getInvoices(filter?: EntityFilter, params?: PaginationParams): Promise<PaginatedResult<SalesInvoice>> {
    return await this.salesInvoiceRepository.findAll(filter, params);
  }

  async createInvoice(
    invoice: Omit<SalesInvoice, 'id' | 'created_at' | 'updated_at' | 'warehouse_id'>,
    lines: Omit<SalesInvoiceLine, 'id' | 'created_at' | 'updated_at'>[],
    warehouseId: string,
    repIssuance?: RepIssuanceOptions,
    creditOverride?: CreditOverride
  ): Promise<SalesInvoice> {
    // Phase 2.5 — a customer who would exceed their credit limit is blocked
    // from further credit sales until explicitly overridden by someone
    // other than whoever requested the sale (segregation of duties). Cash/
    // bank sales never touch the limit; credit_limit left unset (null)
    // means "no limit configured", not "unlimited by policy default" —
    // treated the same as unlimited here since that's an explicit admin choice.
    if (invoice.payment_method === 'credit') {
      const customer = await this.customerRepository.findById(invoice.customer_id);
      if (customer?.credit_limit != null) {
        const outstanding = await this.getCustomerOutstandingBalance(invoice.customer_id);
        if (outstanding + Number(invoice.total) > Number(customer.credit_limit)) {
          if (!creditOverride) {
            throw new Error(
              `تم رفض البيع الآجل: يتجاوز حد ائتمان العميل (الحد: ${customer.credit_limit}, الرصيد الحالي: ${outstanding.toFixed(2)}, قيمة الفاتورة: ${invoice.total}). يلزم اعتماد مدير لتجاوز الحد.`
            );
          }
          assertSegregationOfDuties({
            requestedBy: creditOverride.requestedBy,
            actingUserId: creditOverride.approvedBy,
            action: 'اعتماد تجاوز حد الائتمان'
          });
        }
      }
    }

    // warehouse_id drives RLS branch-scoping on sales_invoices (NOT NULL —
    // every invoice must be attributed to the branch it was sold from), so
    // it's derived from the warehouseId param rather than left for the
    // caller to set independently on the invoice object. rep_user_id is set
    // only for a van sale, so reports can split field vs counter sales.
    const newInvoice = await this.salesInvoiceRepository.create({
      ...invoice,
      warehouse_id: warehouseId,
      rep_user_id: repIssuance?.repUserId ?? null
    });
    await queueOfflineWrite('sales_invoices', 'insert', newInvoice.id, newInvoice);

    const createdLines: SalesInvoiceLine[] = [];
    for (const line of lines) {
      const newLine = await this.salesInvoiceLineRepository.create({
        ...line,
        invoice_id: newInvoice.id
      });
      await queueOfflineWrite('sales_invoice_lines', 'insert', newLine.id, newLine);
      createdLines.push(newLine);

      // A rep-issuance sale deducts the rep's own stock-in-hand ledger
      // instead of the warehouse — that stock already left the warehouse at
      // issuance time (see RepLedgerService.issueStockToRep), so posting a
      // second warehouse deduction here would double-count it.
      if (!repIssuance) {
        // Deduct finished-goods stock, mirroring Sales.tsx handleSaveInvoice:
        // movement_type 'sale_out', negative qty, linked back to the invoice.
        const movement = await this.stockMovementRepository.create({
          item_id: newLine.item_id,
          warehouse_id: warehouseId,
          qty: -Math.abs(newLine.qty),
          movement_type: 'sale_out',
          batch_no: newInvoice.invoice_no,
          ref_table: 'sales_invoices',
          ref_id: newInvoice.id,
          moved_at: new Date().toISOString()
        });
        await queueOfflineWrite('stock_movements', 'insert', movement.id, movement);
      }
    }

    if (repIssuance) {
      await this.repLedgerService.recordSaleFromRepStock(
        repIssuance.repUserId,
        warehouseId,
        createdLines.map((l) => ({ item_id: l.item_id, qty: l.qty })),
        newInvoice.id
      );
      if (newInvoice.payment_method === 'cash') {
        await this.repLedgerService.recordCashCollection(
          repIssuance.repUserId,
          newInvoice.total,
          'cash',
          'sales_invoices',
          newInvoice.id
        );
      }
    }

    // Journal entry, mirroring Sales.tsx handleSaveInvoice: cash sales debit
    // the 'cash' category account, credit sales debit 'ar' (accounts
    // receivable); both credit the 'revenue' account for the invoice total.
    const revenueAcc = (await this.accountRepository.findByCategory('revenue'))[0]?.id;
    if (!revenueAcc) {
      throw new Error(`تعذر تسجيل القيد المحاسبي لفاتورة المبيعات ${newInvoice.invoice_no}: حساب الإيرادات غير موجود`);
    } else if (newInvoice.payment_method === 'cash') {
      const cashAcc = (await this.accountRepository.findByCategory('cash'))[0]?.id;
      if (!cashAcc) {
        throw new Error(`تعذر تسجيل القيد المحاسبي لفاتورة المبيعات ${newInvoice.invoice_no}: حساب النقدية غير موجود`);
      }
      await postDoubleEntry({
        refTable: 'sales_invoices',
        refId: newInvoice.id,
        debitAccountId: cashAcc,
        creditAccountId: revenueAcc,
        amount: newInvoice.total,
        date: newInvoice.date,
        warehouseId
      });
    } else if (newInvoice.payment_method === 'credit') {
      const arAcc = (await this.accountRepository.findByCategory('ar'))[0]?.id;
      if (!arAcc) {
        throw new Error(`تعذر تسجيل القيد المحاسبي لفاتورة المبيعات ${newInvoice.invoice_no}: حساب المدينين غير موجود`);
      }
      await postDoubleEntry({
        refTable: 'sales_invoices',
        refId: newInvoice.id,
        debitAccountId: arAcc,
        creditAccountId: revenueAcc,
        amount: newInvoice.total,
        date: newInvoice.date,
        warehouseId
      });
    }

    return newInvoice;
  }

  async updateInvoice(id: string, invoice: Partial<SalesInvoice>): Promise<SalesInvoice> {
    const updatedInvoice = await this.salesInvoiceRepository.update(id, invoice);
    await queueOfflineWrite('sales_invoices', 'update', id, updatedInvoice);
    return updatedInvoice;
  }

  async deleteInvoice(id: string): Promise<void> {
    await this.salesInvoiceRepository.delete(id);
    await queueOfflineWrite('sales_invoices', 'delete', id, { id });
  }

  async getInvoiceLines(invoiceId: string): Promise<SalesInvoiceLine[]> {
    return await this.salesInvoiceLineRepository.findByInvoiceId(invoiceId);
  }

  async createSalesReturn(
    returnData: Omit<SalesReturn, 'id' | 'created_at' | 'updated_at'>,
    lines: Omit<SalesReturnLine, 'id' | 'created_at' | 'updated_at'>[]
  ): Promise<SalesReturn> {
    const newReturn = await this.salesReturnRepository.create(returnData);
    await queueOfflineWrite('sales_returns', 'insert', newReturn.id, newReturn);

    for (const line of lines) {
      const newLine = await this.salesReturnLineRepository.create({
        ...line,
        return_id: newReturn.id
      });
      await queueOfflineWrite('sales_return_lines', 'insert', newLine.id, newLine);
    }

    // NOTE: stock-movement (adding returned qty back to stock) and journal-entry
    // (Revenue/AR reversal) side effects are intentionally left in the Sales
    // component for this pass, matching createInvoice above.

    return newReturn;
  }

  async getReceiptVouchers(filter?: EntityFilter, params?: PaginationParams): Promise<PaginatedResult<ReceiptVoucher>> {
    return await this.receiptVoucherRepository.findAll(filter, params);
  }

  async createReceiptVoucher(voucher: Omit<ReceiptVoucher, 'id' | 'created_at' | 'updated_at'>): Promise<ReceiptVoucher> {
    const newVoucher = await this.receiptVoucherRepository.create(voucher);
    await queueOfflineWrite('receipt_vouchers', 'insert', newVoucher.id, newVoucher);

    // Mirrors Sales.tsx handleSaveReceiptVoucher: mark the linked invoice
    // paid/partially_paid based on the sum of receipt vouchers applied to it.
    if (newVoucher.invoice_id) {
      const invoice = await this.salesInvoiceRepository.findById(newVoucher.invoice_id);
      if (invoice) {
        const customerVouchers = await this.receiptVoucherRepository.findByCustomerId(invoice.customer_id);
        const totalPaid = customerVouchers
          .filter((v) => v.invoice_id === invoice.id)
          .reduce((sum, v) => sum + Number(v.amount), 0);
        const status = totalPaid >= invoice.total ? 'paid' : 'partially_paid';

        const updatedInvoice = await this.salesInvoiceRepository.update(invoice.id, { status });
        await queueOfflineWrite('sales_invoices', 'update', invoice.id, updatedInvoice);
      }
    }

    // Journal entry, mirroring Sales.tsx: debit Cash/Bank (the voucher's
    // account), credit AR.
    const arAcc = (await this.accountRepository.findByCategory('ar'))[0]?.id;
    if (!arAcc) {
      console.warn('Accounts receivable account not found, skipping journal entry for receipt voucher:', newVoucher.id);
    } else {
      await postDoubleEntry({
        refTable: 'receipt_vouchers',
        refId: newVoucher.id,
        debitAccountId: newVoucher.account_id,
        creditAccountId: arAcc,
        amount: newVoucher.amount,
        date: newVoucher.date
      });
    }

    return newVoucher;
  }

  // Ported from Sales.tsx's runCustomerStatement: opening balance (dated at
  // customer registration) + invoices (debit = total) + receipt vouchers
  // (credit = amount) + sales returns (credit = total), filtered to the date
  // range, sorted chronologically for a running balance, then returned
  // newest-first to match the component's display order.
  // Current running balance (opening balance + invoices - receipts -
  // returns), all-time — the figure the credit-limit check above compares
  // against. Deliberately NOT date-ranged (unlike getCustomerStatement),
  // since a credit decision needs the true current balance, not a window.
  async getCustomerOutstandingBalance(customerId: string): Promise<number> {
    const customer = await this.customerRepository.findById(customerId);
    if (!customer) return 0;

    const invoices = await this.salesInvoiceRepository.findByCustomerId(customerId);
    const vouchers = await this.receiptVoucherRepository.findByCustomerId(customerId);
    const returnsResult = await this.salesReturnRepository.findAll(
      { customer_id: customerId },
      { page: 1, limit: Number.MAX_SAFE_INTEGER }
    );

    const invoicesTotal = invoices.filter((i) => i.status !== 'cancelled').reduce((sum, i) => sum + Number(i.total), 0);
    const receiptsTotal = vouchers.reduce((sum, v) => sum + Number(v.amount), 0);
    const returnsTotal = returnsResult.data.reduce((sum, r) => sum + Number(r.total), 0);

    return Number(customer.opening_balance || 0) + invoicesTotal - receiptsTotal - returnsTotal;
  }

  // Phase 2.5/6.6 — aging buckets (0-30/31-60/61-90/90+ days overdue) across
  // all customers, for the accounts-receivable risk view.
  async getCustomerAgingReport(): Promise<{
    customer_id: string;
    name: string;
    bucket_0_30: number;
    bucket_31_60: number;
    bucket_61_90: number;
    bucket_90_plus: number;
    total: number;
  }[]> {
    const customers = (await this.customerRepository.findAll(undefined, { page: 1, limit: Number.MAX_SAFE_INTEGER })).data;
    const today = new Date();

    const result = [];
    for (const customer of customers) {
      const invoices = (await this.salesInvoiceRepository.findByCustomerId(customer.id))
        .filter((i) => i.status === 'unpaid' || i.status === 'partially_paid');

      const buckets = { bucket_0_30: 0, bucket_31_60: 0, bucket_61_90: 0, bucket_90_plus: 0 };
      for (const inv of invoices) {
        const ageDays = Math.floor((today.getTime() - new Date(inv.date).getTime()) / (1000 * 3600 * 24));
        const amount = Number(inv.total);
        if (ageDays <= 30) buckets.bucket_0_30 += amount;
        else if (ageDays <= 60) buckets.bucket_31_60 += amount;
        else if (ageDays <= 90) buckets.bucket_61_90 += amount;
        else buckets.bucket_90_plus += amount;
      }

      const total = buckets.bucket_0_30 + buckets.bucket_31_60 + buckets.bucket_61_90 + buckets.bucket_90_plus;
      if (total > 0) {
        result.push({ customer_id: customer.id, name: customer.name, ...buckets, total });
      }
    }
    return result;
  }

  async getCustomerStatement(customerId: string, startDate: string, endDate: string): Promise<CustomerStatementEntry[]> {
    const customer = await this.customerRepository.findById(customerId);
    if (!customer) return [];

    type Entry = Omit<CustomerStatementEntry, 'balance'>;
    const transactions: Entry[] = [];

    transactions.push({
      date: customer.created_at.split('T')[0],
      type: 'opening_balance',
      description: 'الرصيد الافتتاحي عند التسجيل',
      debit: Number(customer.opening_balance) || 0,
      credit: 0
    });

    const invoices = await this.salesInvoiceRepository.findByCustomerId(customerId);
    for (const inv of invoices) {
      transactions.push({
        date: inv.date,
        type: 'sales_invoice',
        description: `فاتورة مبيعات رقم ${inv.invoice_no}`,
        debit: Number(inv.total) || 0,
        credit: 0
      });
    }

    const vouchers = await this.receiptVoucherRepository.findByCustomerId(customerId);
    for (const v of vouchers) {
      transactions.push({
        date: v.date,
        type: 'receipt_voucher',
        description: `سند قبض رقم ${v.voucher_no}`,
        debit: 0,
        credit: Number(v.amount) || 0
      });
    }

    const returnsResult = await this.salesReturnRepository.findAll(
      { customer_id: customerId },
      { page: 1, limit: Number.MAX_SAFE_INTEGER }
    );
    for (const r of returnsResult.data) {
      transactions.push({
        date: r.date,
        type: 'sales_return',
        description: `مرتجع مبيعات رقم ${r.return_no}`,
        debit: 0,
        credit: Number(r.total) || 0
      });
    }

    let filtered = transactions;
    if (startDate) {
      filtered = filtered.filter((t) => t.date >= startDate);
    }
    if (endDate) {
      filtered = filtered.filter((t) => t.date <= endDate);
    }

    const chronological = [...filtered].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

    let balance = 0;
    const withBalance: CustomerStatementEntry[] = chronological.map((t) => {
      balance += t.debit - t.credit;
      return { ...t, balance };
    });

    return withBalance.reverse();
  }
}
